<?php

use Illuminate\Database\Seeder;

class SystemConfigurationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('system_configurations')->delete();
        
        \DB::table('system_configurations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => 0,
                'pid' => 1,
                'sign' => 'system',
                'name' => '系统相关',
                'description' => '所有的系统设置都放这里',
                'value' => NULL,
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => 0,
                'pid' => 1,
                'sign' => 'lottery',
                'name' => '彩票相关',
                'description' => '所有的彩票设置都放这里',
                'value' => NULL,
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 0,
                'pid' => 1,
                'sign' => 'fund',
                'name' => '资金相关',
                'description' => '所有的资金设置都放这里',
                'value' => NULL,
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'parent_id' => 0,
                'pid' => 1,
                'sign' => 'admin_fund_control',
                'name' => '管理员金额相关',
                'description' => '管理员金额的设置都放这里',
                'value' => NULL,
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'parent_id' => 0,
                'pid' => 1,
                'sign' => 'app_download_urls',
                'name' => 'app下载地址相关',
                'description' => '应用下载地址相关',
                'value' => NULL,
                'add_admin_id' => 1,
                'last_update_admin_id' => 1,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'parent_id' => 0,
                'pid' => 1,
                'sign' => 'issue',
                'name' => '奖期相关',
                'description' => '奖期相关的所有配置',
                'value' => NULL,
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'parent_id' => 2,
                'pid' => 1,
                'sign' => 'min_bet_prize_group',
                'name' => '最低投注奖金组',
                'description' => '最低投注奖金组.',
                'value' => '1800',
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'parent_id' => 2,
                'pid' => 1,
                'sign' => 'max_bet_prize_group',
                'name' => '最高投注奖金组',
                'description' => '最高投注奖金组',
                'value' => '1960',
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'parent_id' => 2,
                'pid' => 1,
                'sign' => 'min_user_prize_group',
                'name' => '最低开户奖金组',
                'description' => '最低开户奖金组',
                'value' => '1800',
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'parent_id' => 2,
                'pid' => 1,
                'sign' => 'max_user_prize_group',
                'name' => '最高开户奖金组',
                'description' => '最高开户奖金组',
                'value' => '1960',
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'parent_id' => 3,
                'pid' => 1,
                'sign' => 'max_withdraw',
                'name' => '最大提现次数',
                'description' => '最大提现次数',
                'value' => '5000',
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'parent_id' => 4,
                'pid' => 1,
                'sign' => 'admin_recharge_daily_limit',
                'name' => '每日管理员充值限制金额',
                'description' => '每日管理员充值限制金额',
                'value' => '90000',
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'parent_id' => 5,
                'pid' => 1,
                'sign' => 'app_download_url',
                'name' => 'app下载地址',
                'description' => '应用下载地址',
                'value' => 'http://www.lottery.com/api/download',
                'add_admin_id' => 1,
                'last_update_admin_id' => 1,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'parent_id' => 5,
                'pid' => 1,
                'sign' => 'app_version',
                'name' => 'app 版本',
                'description' => '应用版本',
                'value' => '1.0',
                'add_admin_id' => 1,
                'last_update_admin_id' => 1,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'parent_id' => 6,
                'pid' => 1,
                'sign' => 'generate_issue_time',
                'name' => '生成奖期时间',
                'description' => '每天自动生成奖期的时间',
                'value' => '00:00',
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'parent_id' => 3,
                'pid' => 1,
                'sign' => 'binding_bankcard_number',
                'name' => '用户可绑定的银行卡数量',
                'description' => '用户可绑定的银行卡数量',
                'value' => '4',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'display' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 31,
                'parent_id' => 2,
                'pid' => 1,
                'sign' => 'max_profit_bonus',
                'name' => '最大盈利奖金',
                'description' => '最大盈利奖金',
                'value' => '350000',
                'add_admin_id' => 24,
                'last_update_admin_id' => 24,
                'status' => 1,
                'display' => 1,
                'created_at' => '2019-07-25 15:34:15',
                'updated_at' => '2019-07-25 15:35:39',
            ),
            17 => 
            array (
                'id' => 32,
                'parent_id' => 0,
                'pid' => 1,
                'sign' => 'dd',
                'name' => 'xuanwu',
                'description' => '2——2',
                'value' => NULL,
                'add_admin_id' => 4,
                'last_update_admin_id' => 4,
                'status' => 1,
                'display' => 1,
                'created_at' => '2019-07-29 18:14:05',
                'updated_at' => '2019-07-29 18:14:05',
            ),
        ));
        
        
    }
}